CREATE TABLE SERVICOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Codigo VARCHAR(255) UNIQUE NOT NULL,
    tipo VARCHAR(255),
    preco DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT TRUE
)