CREATE TABLE SERVICOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    codigo CHAR(2) UNIQUE NOT NULL,
    tipo VARCHAR(50),
    preco DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT TRUE
)